spring:
  application:
    name: service-a
  
server:
  port: 8800

eureka:
  instance: 
    instance-id: inst001                          # 동일한 서비스내에서 인스턴스를 식별하기 위한 ID
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka 클라이언트가 속할 Zone 정의